In [73]:
import csv

import pandas as pd

import numpy as np

import torch

from torch import nn, optim

from torch.autograd import Variable

from torch.utils.data import Dataset

from torch.utils.data import DataLoader

In [95]:
# 定义自己的类
class MyDataset(Dataset):
    
    # 初始化
    def __init__(self, file_name):
        # 读入数据
        self.data = pd.read_csv(file_name)
    
    # 返回df的长度
    def __len__(self):
        return len(self.data)
    
    # 获取第idx+1列的数据
    def __getitem__(self, idx):
        return self.data.values[idx,1:10]

# 通过实例化对象来访问该类
# 假设同目录下存在名为median_benchmark.csv的文件
ds = MyDataset('formatweather.csv')
ds=np.asarray(ds[:], dtype = np.float32)#####源文件float32 ,不知道为什么读取变为float64，这里再进行处理
##dl = DataLoader(ds, batch_size=100, shuffle=False)

#####处理为torch，分为trainx，trainy
torchds=torch.from_numpy(ds[:])

dl = DataLoader(torchds, batch_size=100, shuffle=False)

In [97]:
class Cnn(nn.Module):

    def __init__(self, in_dim, n_class):

        super(Cnn, self).__init__()

        self.conv = nn.Sequential(

            nn.Conv2d(in_dim, 6, (1,2), stride=(1), padding=(0,1)),#6,1,9

            nn.ReLU(True),

            nn.MaxPool2d(1, 1),#6,1,9

            nn.Conv2d(6, 16, (1,3), stride=(1), padding=(0,1)),

            nn.ReLU(True), nn.MaxPool2d(1, 1))#16,1,9
   
            #5*144

        self.fc = nn.Sequential(

            nn.Linear(144, 16), nn.Linear(16, 8), nn.Linear(8, n_class))



    def forward(self, x):

        out = self.conv(x)

        out = out.view(out.size(0), -1)

        out = self.fc(out)
        
        #out = out.view(5)

        return out

In [107]:
model = Cnn(1, 1)
##model.load_state_dict(torch.load('./weathercnn.pth'))
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [108]:
for epoch in range(100):
 
    print('epoch {}'.format(epoch + 1))

    print('*' * 10)

    running_loss = 0.0

    for i, data in enumerate(dl, 1):
        
            train_x=data[:,0:8]
            
            train_x=train_x.view(-1,1,1,8)
            
            train_y=data[:,8]
            
            train_y=train_y.view(-1,1)
            
            train_x=Variable(train_x)
            
            train_y=Variable(train_y)
        
            out = model(train_x)

            loss = criterion(out, train_y)
            
            running_loss += loss * train_y.size(0)

            # 向后传播

            optimizer.zero_grad()

            loss.backward()

            optimizer.step()
            
           
                
    print('loss:-------')
    print(loss)
    #print(running_loss)
            
    print(out,train_y)

epoch 1
**********
loss:-------
tensor(0.0067, grad_fn=<MseLossBackward>)
tensor([[0.0938],
        [0.0937],
        [0.0935],
        [0.0935],
        [0.0932],
        [0.0929],
        [0.0925],
        [0.0924],
        [0.0923],
        [0.0922],
        [0.0921],
        [0.0919],
        [0.0919],
        [0.0914],
        [0.0913],
        [0.0912],
        [0.0912],
        [0.0911],
        [0.0909],
        [0.0907],
        [0.0907],
        [0.0906],
        [0.0906]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 2
**********
loss:-------
tensor(0.0066, grad_fn=<MseLossBackward

        [0.0121]])
epoch 10
**********
loss:-------
tensor(0.0061, grad_fn=<MseLossBackward>)
tensor([[0.0906],
        [0.0904],
        [0.0902],
        [0.0899],
        [0.0897],
        [0.0894],
        [0.0888],
        [0.0884],
        [0.0882],
        [0.0882],
        [0.0880],
        [0.0879],
        [0.0879],
        [0.0877],
        [0.0876],
        [0.0874],
        [0.0873],
        [0.0870],
        [0.0869],
        [0.0867],
        [0.0866],
        [0.0865],
        [0.0864]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 11
**********
loss:-------
tensor(0.0060, gra

        [0.0121]])
epoch 19
**********
loss:-------
tensor(0.0055, grad_fn=<MseLossBackward>)
tensor([[0.0879],
        [0.0873],
        [0.0872],
        [0.0865],
        [0.0862],
        [0.0860],
        [0.0851],
        [0.0842],
        [0.0840],
        [0.0840],
        [0.0839],
        [0.0838],
        [0.0840],
        [0.0842],
        [0.0839],
        [0.0837],
        [0.0831],
        [0.0826],
        [0.0825],
        [0.0821],
        [0.0819],
        [0.0817],
        [0.0815]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 20
**********
loss:-------
tensor(0.0054, gra

        [0.0121]])
epoch 28
**********
loss:-------
tensor(0.0048, grad_fn=<MseLossBackward>)
tensor([[0.0842],
        [0.0833],
        [0.0832],
        [0.0820],
        [0.0816],
        [0.0815],
        [0.0804],
        [0.0790],
        [0.0787],
        [0.0787],
        [0.0785],
        [0.0784],
        [0.0789],
        [0.0795],
        [0.0792],
        [0.0788],
        [0.0776],
        [0.0768],
        [0.0765],
        [0.0761],
        [0.0756],
        [0.0754],
        [0.0751]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 29
**********
loss:-------
tensor(0.0047, gra

        [0.0121]])
epoch 37
**********
loss:-------
tensor(0.0038, grad_fn=<MseLossBackward>)
tensor([[0.0791],
        [0.0778],
        [0.0776],
        [0.0756],
        [0.0752],
        [0.0753],
        [0.0738],
        [0.0715],
        [0.0711],
        [0.0712],
        [0.0709],
        [0.0709],
        [0.0718],
        [0.0733],
        [0.0728],
        [0.0721],
        [0.0699],
        [0.0685],
        [0.0680],
        [0.0675],
        [0.0667],
        [0.0664],
        [0.0658]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 38
**********
loss:-------
tensor(0.0037, gra

        [0.0121]])
epoch 46
**********
loss:-------
tensor(0.0026, grad_fn=<MseLossBackward>)
tensor([[0.0712],
        [0.0689],
        [0.0688],
        [0.0652],
        [0.0652],
        [0.0658],
        [0.0640],
        [0.0604],
        [0.0598],
        [0.0599],
        [0.0594],
        [0.0597],
        [0.0612],
        [0.0644],
        [0.0635],
        [0.0622],
        [0.0580],
        [0.0557],
        [0.0551],
        [0.0544],
        [0.0531],
        [0.0526],
        [0.0516]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 47
**********
loss:-------
tensor(0.0025, gra

        [0.0121]])
epoch 55
**********
loss:-------
tensor(0.0012, grad_fn=<MseLossBackward>)
tensor([[0.0578],
        [0.0542],
        [0.0550],
        [0.0483],
        [0.0490],
        [0.0506],
        [0.0486],
        [0.0428],
        [0.0420],
        [0.0423],
        [0.0415],
        [0.0426],
        [0.0458],
        [0.0515],
        [0.0500],
        [0.0481],
        [0.0407],
        [0.0371],
        [0.0364],
        [0.0355],
        [0.0335],
        [0.0329],
        [0.0312]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 56
**********
loss:-------
tensor(0.0010, gra

        [0.0121]])
epoch 64
**********
loss:-------
tensor(0.0001, grad_fn=<MseLossBackward>)
tensor([[ 0.0317],
        [ 0.0274],
        [ 0.0306],
        [ 0.0197],
        [ 0.0193],
        [ 0.0218],
        [ 0.0187],
        [ 0.0114],
        [ 0.0104],
        [ 0.0109],
        [ 0.0098],
        [ 0.0124],
        [ 0.0175],
        [ 0.0226],
        [ 0.0206],
        [ 0.0191],
        [ 0.0095],
        [ 0.0055],
        [ 0.0053],
        [ 0.0032],
        [ 0.0016],
        [ 0.0010],
        [-0.0015]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 65
**********
loss:---

        [-1.5089e-02]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 73
**********
loss:-------
tensor(0.0002, grad_fn=<MseLossBackward>)
tensor([[ 0.0161],
        [ 0.0128],
        [ 0.0181],
        [ 0.0057],
        [ 0.0042],
        [ 0.0058],
        [ 0.0020],
        [-0.0033],
        [-0.0043],
        [-0.0051],
        [-0.0071],
        [-0.0037],
        [ 0.0014],
        [ 0.0012],
        [-0.0013],
        [-0.0016],
        [-0.0082],
        [-0.0106],
        [-0.0103],
        [-0.0130],
        [-0.0127],
        [-0.0132],
        [-0.0152]], grad_fn=<AddmmBackward>

        [0.0121]])
epoch 81
**********
loss:-------
tensor(0.0002, grad_fn=<MseLossBackward>)
tensor([[ 0.0129],
        [ 0.0107],
        [ 0.0169],
        [ 0.0048],
        [ 0.0033],
        [ 0.0044],
        [ 0.0009],
        [-0.0022],
        [-0.0030],
        [-0.0048],
        [-0.0071],
        [-0.0034],
        [ 0.0003],
        [-0.0031],
        [-0.0060],
        [-0.0053],
        [-0.0096],
        [-0.0102],
        [-0.0092],
        [-0.0120],
        [-0.0105],
        [-0.0109],
        [-0.0124]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 82
**********
loss:---

        [-7.6174e-03]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 90
**********
loss:-------
tensor(0.0002, grad_fn=<MseLossBackward>)
tensor([[ 0.0119],
        [ 0.0107],
        [ 0.0175],
        [ 0.0059],
        [ 0.0047],
        [ 0.0056],
        [ 0.0025],
        [ 0.0010],
        [ 0.0003],
        [-0.0020],
        [-0.0044],
        [-0.0006],
        [ 0.0022],
        [-0.0030],
        [-0.0060],
        [-0.0047],
        [-0.0074],
        [-0.0068],
        [-0.0053],
        [-0.0080],
        [-0.0057],
        [-0.0059],
        [-0.0071]], grad_fn=<AddmmBackward>

        [0.0121]])
epoch 98
**********
loss:-------
tensor(0.0001, grad_fn=<MseLossBackward>)
tensor([[ 0.0116],
        [ 0.0110],
        [ 0.0181],
        [ 0.0068],
        [ 0.0058],
        [ 0.0067],
        [ 0.0040],
        [ 0.0032],
        [ 0.0027],
        [ 0.0002],
        [-0.0022],
        [ 0.0017],
        [ 0.0042],
        [-0.0018],
        [-0.0048],
        [-0.0031],
        [-0.0050],
        [-0.0039],
        [-0.0022],
        [-0.0048],
        [-0.0021],
        [-0.0023],
        [-0.0032]], grad_fn=<AddmmBackward>) tensor([[0.0111],
        [0.0201],
        [0.0091],
        [0.0080],
        [0.0091],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0080],
        [0.0070],
        [0.0121],
        [0.0171],
        [0.0111],
        [0.0091],
        [0.0111],
        [0.0080],
        [0.0091],
        [0.0101],
        [0.0080],
        [0.0101],
        [0.0101],
        [0.0080],
        [0.0121]])
epoch 99
**********
loss:---

In [106]:
train_y.size()

torch.Size([23, 1])

In [104]:
# 保存模型
torch.save(model.state_dict(), './originalweathercnn.pth')

In [12]:
out[120:150]

tensor([[0.1062],
        [0.1069],
        [0.1067],
        [0.1068],
        [0.1067],
        [0.1066],
        [0.1066],
        [0.1067],
        [0.1064],
        [0.1060],
        [0.1058],
        [0.1055],
        [0.1053],
        [0.1042],
        [0.1040],
        [0.1016],
        [0.1038],
        [0.1040],
        [0.1043],
        [0.1030],
        [0.1049],
        [0.1057],
        [0.1059],
        [0.1061],
        [0.1060],
        [0.1038],
        [0.1038],
        [0.1052],
        [0.1056],
        [0.1054]], grad_fn=<SliceBackward>)

In [13]:
train_y[10:15]

tensor([[0.0992],
        [0.0992],
        [0.0992],
        [0.0992],
        [0.0992]])

In [ ]:
x=np.array([[0.129779 ,0.352941 ,0.245902 ,0.527273 ,0.666667 ,0.002290 ,0.000000 ,0.0],  
        [0.148893 ,0.367647 ,0.245902 ,0.527273 ,0.666667 ,0.003811 ,0.000000 ,0.0],
        [0.159960 ,0.426471 ,0.229508 ,0.545454 ,0.666667 ,0.005332 ,0.000000 ,0.0],
        [0.182093 ,0.485294 ,0.229508 ,0.563637 ,0.666667 ,0.008391 ,0.037037 ,0.0],
        [0.138833 ,0.485294 ,0.229508 ,0.563637 ,0.666667 ,0.009912 ,0.074074 ,0.0]],dtype = np.float32)
y=np.array([0.1 ,0.1 ,0.1 ,0.1 ,0.1])