In [7]:
import pandas as pd
import numpy as np
import time
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

In [9]:
def parse(x):
    return pd.datetime.strptime(x, '%Y %m %d %H')
df = pd.read_csv('test.csv',  parse_dates = {'date':[1,2,3,4]} ,index_col='No', date_parser=parse,skiprows=0)
#print(df.dropna(axis=0,how='any'))#0对行进行操作 1对列进行操作 any:只要存在NaN即可drop掉 all:必须全部是NaN才可drop
#df=df.dropna(axis=0,how='any')
df.fillna(df.mean())

date       pm2.5  DEWP  TEMP  PRES cbwd    Iws  Is  Ir
No                                                                       
1   2010-01-01 00:00:00   88.869318   -21   -11  1021   NW   1.79   0   0
2   2010-01-01 01:00:00   88.869318   -21   -12  1020   NW   4.92   0   0
3   2010-01-01 02:00:00   88.869318   -21   -11  1019   NW   6.71   0   0
4   2010-01-01 03:00:00   88.869318   -21   -14  1019   NW   9.84   0   0
5   2010-01-01 04:00:00   88.869318   -20   -12  1018   NW  12.97   0   0
6   2010-01-01 05:00:00   88.869318   -19   -10  1017   NW  16.10   0   0
7   2010-01-01 06:00:00   88.869318   -19    -9  1017   NW  19.23   0   0
8   2010-01-01 07:00:00   88.869318   -19    -9  1017   NW  21.02   0   0
9   2010-01-01 08:00:00   88.869318   -19    -9  1017   NW  24.15   0   0
10  2010-01-01 09:00:00   88.869318   -20    -8  1017   NW  27.28   0   0
11  2010-01-01 10:00:00   88.869318   -19    -7  1017   NW  31.30   0   0
12  2010-01-01 11:00:00   88.869318   -18    -5  1017   NW  34.43   0   0
13  2010-01-01 12:00:00   88.869318   -19    -5  1015   NW  37.56   0   0
14  2010-01-01 13:00:00   88.869318   -18    -3  1015   NW  40.69   0   0
15  2010-01-01 14:00:00   88.869318   -18    -2  1014   NW  43.82   0   0
16  2010-01-01 15:00:00   88.869318   -18    -1  1014   cv   0.89   0   0
17  2010-01-01 16:00:00   88.869318   -19    -2  1015   NW   1.79   0   0
18  2010-01-01 17:00:00   88.869318   -18    -3  1015   NW   2.68   0   0
19  2010-01-01 18:00:00   88.869318   -18    -5  1016   NE   1.79   0   0
20  2010-01-01 19:00:00   88.869318   -17    -4  1017   NW   1.79   0   0
21  2010-01-01 20:00:00   88.869318   -17    -5  1017   cv   0.89   0   0
22  2010-01-01 21:00:00   88.869318   -17    -5  1018   NW   1.79   0   0
23  2010-01-01 22:00:00   88.869318   -17    -5  1018   NW   2.68   0   0
24  2010-01-01 23:00:00   88.869318   -17    -5  1020   cv   0.89   0   0
25  2010-01-02 00:00:00  129.000000   -16    -4  1020   SE   1.79   0   0
26  2010-01-02 01:00:00  148.000000   -15    -4  1020   SE   2.68   0   0
27  2010-01-02 02:00:00  159.000000   -11    -5  1021   SE   3.57   0   0
28  2010-01-02 03:00:00  181.000000    -7    -5  1022   SE   5.36   1   0
29  2010-01-02 04:00:00  138.000000    -7    -5  1022   SE   6.25   2   0
30  2010-01-02 05:00:00  109.000000    -7    -6  1022   SE   7.14   3   0
..                  ...         ...   ...   ...   ...  ...    ...  ..  ..
171 2010-01-08 02:00:00  275.000000   -20   -16  1031   NE   0.89   0   0
172 2010-01-08 03:00:00  164.000000   -19   -15  1030   SE   0.89   0   0
173 2010-01-08 04:00:00  110.000000   -18   -15  1030   cv   0.45   0   0
174 2010-01-08 05:00:00  100.000000   -18   -15  1029   cv   1.34   0   0
175 2010-01-08 06:00:00   81.000000   -18   -15  1029   NW   1.79   0   0
176 2010-01-08 07:00:00   71.000000   -16   -13  1029   NE   0.89   0   0
177 2010-01-08 08:00:00   66.000000   -16   -12  1029   SE   0.89   0   0
178 2010-01-08 09:00:00   92.000000   -16   -12  1030   SE   1.78   0   0
179 2010-01-08 10:00:00  135.000000   -17   -10  1030   NE   0.89   0   0
180 2010-01-08 11:00:00  155.000000   -16   -10  1029   cv   0.89   0   0
181 2010-01-08 12:00:00  198.000000   -16    -9  1028   SE   3.13   0   0
182 2010-01-08 13:00:00  250.000000   -15    -8  1026   SE   4.92   0   0
183 2010-01-08 14:00:00  200.000000   -16    -8  1026   cv   0.89   0   0
184 2010-01-08 15:00:00  231.000000   -16    -8  1025   cv   1.78   0   0
185 2010-01-08 16:00:00  250.000000   -16    -8  1025   cv   2.67   0   0
186 2010-01-08 17:00:00  212.000000   -17    -8  1025   SE   0.89   0   0
187 2010-01-08 18:00:00  219.000000   -17    -9  1026   cv   0.45   0   0
188 2010-01-08 19:00:00  227.000000   -17   -11  1026   cv   1.34   0   0
189 2010-01-08 20:00:00  226.000000   -17   -12  1026   cv   1.79   0   0
190 2010-01-08 21:00:00  225.000000   -18   -14  1027   NW   1.79   0   0
191 2010-01-08 22:00:00  168.000000   -16    -9  1027   NW   4.92   0   0
192 2010-01-08 23:00:00

In [10]:
values = df.values
encoder = LabelEncoder()
values[:,5] = encoder.fit_transform(values[:,5])
values[:,5]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 0, 1, 3, 1,
       1, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 3, 3, 3, 1, 1, 0, 2, 3, 3, 1, 0,
       2, 2, 0, 3, 2, 2, 3, 3, 3, 2, 3, 3, 3, 1, 1, 1, 3, 1, 1, 1, 1, 1,
       1, 1], dtype=object)

In [11]:
values

array([[Timestamp('2010-01-01 00:00:00'), nan, -21, ..., 1.79, 0, 0],
       [Timestamp('2010-01-01 01:00:00'), nan, -21, ..., 4.92, 0, 0],
       [Timestamp('2010-01-01 02:00:00'), nan, -21, ..., 6.71, 0, 0],
       ...,
       [Timestamp('2010-01-09 05:00:00'), 155.0, -19, ..., 13.86, 0, 0],
       [Timestamp('2010-01-09 06:00:00'), 119.0, -18, ..., 17.88, 0, 0],
       [Timestamp('2010-01-09 07:00:00'), 106.0, -19, ..., 21.9, 0, 0]],
      dtype=object)

In [92]:
values[:,0][1]-values[:,0][0]


Timedelta('0 days 01:00:00')

In [93]:
values[:,0][2]-values[:,0][0]

Timedelta('0 days 02:00:00')

In [110]:
type(values[:,0][2])

pandas._libs.tslibs.timestamps.Timestamp

In [72]:
values1 = values[:,1:]
# ensure all data is float
values1 = values1.astype('float32')


In [73]:
values1[0]

array([ 129.  ,  -16.  ,   -4.  , 1020.  ,    2.  ,    1.79,    0.  ,
          0.  ], dtype=float32)

In [74]:
# normalize features
scaler = MinMaxScaler(feature_range=(0, 1))
scaled = scaler.fit_transform(values1)

In [75]:
scaled[0]

array([0.427451  , 0.55      , 1.0000001 , 0.        , 0.6666667 ,
       0.00614341, 0.        , 0.        ], dtype=float32)

In [76]:
# convert series to supervised learning
def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):
	n_vars = 1 if type(data) is list else data.shape[1]
	df = pd.DataFrame(data)
	cols, names = list(), list()
	# input sequence (t-n, ... t-1)
	for i in range(n_in, 0, -1):
		cols.append(df.shift(i))
		names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
	# forecast sequence (t, t+1, ... t+n)
	for i in range(0, n_out):
		cols.append(df.shift(-i))
		if i == 0:
			names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
		else:
			names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
	# put it all together
	agg = pd.concat(cols, axis=1)
	agg.columns = names
	# drop rows with NaN values
	if dropnan:
		agg.dropna(inplace=True)
	return agg


In [77]:
# frame as supervised learning
reframed = series_to_supervised(scaled, 1, 1)
# drop columns we don't want to predict
reframed.drop(reframed.columns[[9,10,11,12,13,14,15]], axis=1, inplace=True)
print(reframed.head())

   var1(t-1)  var2(t-1)  var3(t-1)  var4(t-1)  var5(t-1)  var6(t-1)  \
1   0.427451       0.55   1.000000     0.0000   0.666667   0.006143   
2   0.501961       0.60   1.000000     0.0000   0.666667   0.010224   
3   0.545098       0.80   0.933333     0.0625   0.666667   0.014304   
4   0.631373       1.00   0.933333     0.1250   0.666667   0.022511   
5   0.462745       1.00   0.933333     0.1250   0.666667   0.026591   

   var7(t-1)  var8(t-1)   var1(t)  
1   0.000000        0.0  0.501961  
2   0.000000        0.0  0.545098  
3   0.000000        0.0  0.631373  
4   0.037037        0.0  0.462745  
5   0.074074        0.0  0.349020  


In [78]:
reframed

var1(t-1)  var2(t-1)  var3(t-1)  var4(t-1)  var5(t-1)  var6(t-1)  \
1     0.427451       0.55   1.000000     0.0000   0.666667   0.006143   
2     0.501961       0.60   1.000000     0.0000   0.666667   0.010224   
3     0.545098       0.80   0.933333     0.0625   0.666667   0.014304   
4     0.631373       1.00   0.933333     0.1250   0.666667   0.022511   
5     0.462745       1.00   0.933333     0.1250   0.666667   0.026591   
6     0.349020       1.00   0.866667     0.1250   0.666667   0.030671   
7     0.333333       1.00   0.866667     0.1875   0.666667   0.038878   
8     0.407843       1.00   0.933333     0.2500   0.666667   0.047084   
9     0.392157       0.95   0.866667     0.2500   0.666667   0.055291   
10    0.439216       1.00   0.933333     0.3125   0.666667   0.063497   
11    0.470588       1.00   0.933333     0.3750   0.666667   0.077847   
12    0.517647       0.95   0.933333     0.3750   0.666667   0.092197   
13    0.501961       0.95   0.933333     0.3750   0.666667   0.106547   
14    0.564706       0.95   0.933333     0.3125   0.666667   0.124977   
15    0.541176       0.90   0.933333     0.3125   0.666667   0.143407   
16    0.525490       0.90   0.933333     0.3125   0.666667   0.161838   
17    0.545098       0.90   0.933333     0.3750   0.666667   0.170044   
18    0.564706       0.95   0.933333     0.4375   0.666667   0.178251   
19    0.588235       0.95   0.933333     0.4375   0.666667   0.192600   
20    0.505882       0.95   0.933333     0.5000   0.666667   0.200807   
21    0.525490       1.00   0.933333     0.5000   0.666667   0.209013   
22    0.564706       1.00   0.933333     0.4375   0.666667   0.223363   
23    0.533333       0.95   0.866667     0.5000   0.666667   0.237713   
24    0.415686       0.95   0.866667     0.4375   0.666667   0.252063   
25    0.274510       1.00   0.866667     0.4375   0.666667   0.266413   
26    0.168627       0.95   0.866667     0.3750   0.666667   0.280763   
27    0.176471       0.95   0.800000     0.3750   0.666667   0.299193   
28    0.137255       0.95   0.800000     0.3125   0.666667   0.313543   
29    0.176471       0.95   0.800000     0.2500   0.666667   0.331973   
30    0.247059       0.90   0.733333     0.2500   0.666667   0.350403   
..         ...        ...        ...        ...        ...        ...   
146   0.686275       0.40   0.200000     0.6875   0.333333   0.014350   
147   1.000000       0.35   0.200000     0.6875   0.000000   0.002017   
148   0.564706       0.40   0.266667     0.6250   0.666667   0.002017   
149   0.352941       0.45   0.266667     0.6250   1.000000   0.000000   
150   0.313726       0.45   0.266667     0.5625   1.000000   0.004080   
151   0.239216       0.45   0.266667     0.5625   0.333333   0.006143   
152   0.200000       0.55   0.400000     0.5625   0.000000   0.002017   
153   0.180392       0.55   0.466667     0.5625   0.666667   0.002017   
154   0.282353       0.55   0.466667     0.6250   0.666667   0.006098   
155   0.450980       0.50   0.600000     0.6250   0.000000   0.002017   
156   0.529412       0.55   0.600000     0.5625   1.000000   0.002017   
157   0.698039       0.55   0.666667     0.5000   0.666667   0.012287   
158   0.901961       0.60   0.733333     0.3750   0.666667   0.020493   
159   0.705882       0.55   0.733333     0.3750   1.000000   0.002017   
160   0.827451       0.55   0.733333     0.3125   1.000000   0.006098   
161   0.901961       0.55   0.733333     0.3125   1.000000   0.010178   
162   0.752941       0.50   0.733333     0.3125   0.666667   0.002017   
163   0.780392       0.50   0.666667     0.3750   1.000000   0.000000   
164   0.811765       0.50   0.533333     0.3750   1.000000   0.004080   
165   0.807843       0.50   0.466667     0.3750   1.000000   0.006143   
166   0.803922       0.45   0.333333     0.4375   0.333333   0.006143   
167   0.580392       0.55   0.666667     0.4375   0.333333   0.020493   
168   0.584314       0.55   0.533333     0.4375   0.333333   0.

In [96]:
import time
import datetime

#获取当前时间戳
time.time()
#返回时间戳1470733760.613

1561949533.0229053

In [97]:
#获取localtime
time.localtime()
#time.struct_time(tm_year=2016, tm_mon=8, tm_mday=9, tm_hour=17, tm_min=11, tm_sec=13, tm_wday=1, tm_yday=222, tm_isdst=0)

time.struct_time(tm_year=2019, tm_mon=7, tm_mday=1, tm_hour=10, tm_min=52, tm_sec=22, tm_wday=0, tm_yday=182, tm_isdst=0)

In [102]:
#上面的时间格式不好看，定义一个时间格式
ISOTIMEFORMAT='%Y-%m-%d %X'
#使用strftime做转换
a = time.strftime( ISOTIMEFORMAT, time.localtime() )
#返回'2016-08-09 17:15:27'
a

'2019-07-01 10:54:32'

In [104]:
type(a)##str
b=time.time()
type(b)##float

float

In [107]:
#将'2016-08-09 17:15:27'转化为时间戳
time.mktime(time.strptime(a,ISOTIMEFORMAT))
#1470734127.0

1561949672.0

In [109]:
#获取当前时间的前三天的时间戳
time.mktime((datetime.datetime.now() - datetime.timedelta(days = 0)).timetuple())

1561949835.0

In [5]:
import numpy as np
from sklearn.preprocessing import Imputer
#用均值插补缺失值
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp.fit([[1, 2], [np.nan, 3], [7, 6]])
Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)
X = [[np.nan, 2], [6, np.nan], [7, 6]]
print(imp.transform(X))                           

[[4.         2.        ]
 [6.         3.66666667]
 [7.         6.        ]]


I:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
I:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
